$(PHP_PECL_EXTENSION)_ARTIFACT = $(notdir $($(PHP_PECL_EXTENSION)_DOWNLOAD_URL))

$(PHP_PECL_EXTENSION)_BINARY_RELEASE: $($(PHP_PECL_EXTENSION)_ARTIFACT)
	echo "$(shell curl -fsL $($(PHP_PECL_EXTENSION)_DOWNLOAD_URL).sha256) $<" | sha256sum --check
	tar -xf $($(PHP_PECL_EXTENSION)_ARTIFACT) --strip-components=1 -C $(phplibdir) $(PHP_PECL_EXTENSION).$(SHLIB_SUFFIX_NAME)

$($(PHP_PECL_EXTENSION)_ARTIFACT):
	curl -fsL $($(PHP_PECL_EXTENSION)_DOWNLOAD_URL) -o $@

